#!/bin/bash

echo "Tidy up..."
mkdir -p build
rm -f build/*

echo "Compile nucleus..."
cp ../common-crosscompiler/cross-16kb.fs cross.fs
cp ../common-crosscompiler/instructionset-16kb-quickstore.fs instructionset.fs
gforth cross.fs instructionset.fs nucleus.fs
rm cross.fs instructionset.fs
echo ""

if [ ! -f ../common-crosscompiler/icecreammachine-16kb ]; then
    fpc -XX ../common-crosscompiler/icecreammachine-16kb.pas
fi
echo "Compile additional Forth sources..."
cat ../common-forth/coredefinitions.fs ../common/double.fs ../common/fixpoint.fs basisdefinitions.fs textmode.fs ../common-mch2022/loader.fs ../common-mch2022/sound.fs ../common-forth/insight-16kb.fs sokoace.fs > included.fs
../common-crosscompiler/icecreammachine-16kb build/nucleus.hex build/iceimage.hex included.fs > build/log.txt

md5sum build/nucleus.hex build/iceimage.hex

# convert hex to bin forth image
../../hex-to-bin-le.sh build/iceimage.hex ../../build-tmp/soko-image.bin
